/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./ui-src/models/Heart.glb -o ./ui-src/components/Heart.tsx 
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { Sphere, useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Heart_Full: THREE.Mesh;
  };
  materials: {
    Red: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements["mesh"]>
>;

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "https://nogson.github.io/glb-viewer/ui-src/assets/glb/Heart.glb"
  ) as GLTFResult;
  console.log(nodes);
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Heart_Full.geometry}
        material={materials.Red}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload(
  "https://nogson.github.io/glb-viewer/ui-src/assets/glb/Heart.glb"
);
