/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ui-src/assets/glb/Locker.glb -o ui-src/components/Locker.tsx 
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: any;
  materials: {
    ["wood.001"]: THREE.MeshStandardMaterial;
    silver02: THREE.MeshStandardMaterial;
    silver: THREE.MeshStandardMaterial;
  };
};

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements["mesh"]>
>;

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "https://nogson.github.io/glb-viewer/ui-src/assets/glb/Locker.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cube.geometry}
        material={materials["wood.001"]}
        position={[0, 0.34, 0]}
        scale={[5, 5, 1]}
      />
      <group position={[0, -5.09, 0]}>
        <mesh
          geometry={nodes.Cube002_1.geometry}
          material={materials["wood.001"]}
        />
        <mesh
          geometry={nodes.Cube002_2.geometry}
          material={materials.silver02}
        />
        <mesh geometry={nodes.Cube002_3.geometry} material={materials.silver} />
      </group>
      <group position={[-4.722, 2.425, 1.097]}>
        <mesh
          geometry={nodes.Cube010_1.geometry}
          material={materials["wood.001"]}
        />
        <mesh
          geometry={nodes.Cube010_2.geometry}
          material={materials.silver02}
        />
        <mesh geometry={nodes.Cube010_3.geometry} material={materials.silver} />
      </group>
      <group position={[-4.722, 0.423, 1.097]}>
        <mesh
          geometry={nodes.Cube010_1.geometry}
          material={materials["wood.001"]}
        />
        <mesh
          geometry={nodes.Cube010_2.geometry}
          material={materials.silver02}
        />
        <mesh geometry={nodes.Cube010_3.geometry} material={materials.silver} />
      </group>
      <group position={[-4.722, -1.581, 1.097]}>
        <mesh
          geometry={nodes.Cube010_1.geometry}
          material={materials["wood.001"]}
        />
        <mesh
          geometry={nodes.Cube010_2.geometry}
          material={materials.silver02}
        />
        <mesh geometry={nodes.Cube010_3.geometry} material={materials.silver} />
      </group>
      <group position={[-4.722, -3.576, 1.097]}>
        <mesh
          geometry={nodes.Cube010_1.geometry}
          material={materials["wood.001"]}
        />
        <mesh
          geometry={nodes.Cube010_2.geometry}
          material={materials.silver02}
        />
        <mesh geometry={nodes.Cube010_3.geometry} material={materials.silver} />
      </group>
      <group position={[-2.722, 4.424, 1.097]}>
        <mesh
          geometry={nodes.Cube010_1.geometry}
          material={materials["wood.001"]}
        />
        <mesh
          geometry={nodes.Cube010_2.geometry}
          material={materials.silver02}
        />
        <mesh geometry={nodes.Cube010_3.geometry} material={materials.silver} />
      </group>
      <group position={[-2.722, 2.425, 1.097]}>
        <mesh
          geometry={nodes.Cube010_1.geometry}
          material={materials["wood.001"]}
        />
        <mesh
          geometry={nodes.Cube010_2.geometry}
          material={materials.silver02}
        />
        <mesh geometry={nodes.Cube010_3.geometry} material={materials.silver} />
      </group>
      <group position={[-2.722, 0.423, 1.097]}>
        <mesh
          geometry={nodes.Cube010_1.geometry}
          material={materials["wood.001"]}
        />
        <mesh
          geometry={nodes.Cube010_2.geometry}
          material={materials.silver02}
        />
        <mesh geometry={nodes.Cube010_3.geometry} material={materials.silver} />
      </group>
      <group position={[-2.722, -1.581, 1.097]}>
        <mesh
          geometry={nodes.Cube010_1.geometry}
          material={materials["wood.001"]}
        />
        <mesh
          geometry={nodes.Cube010_2.geometry}
          material={materials.silver02}
        />
        <mesh geometry={nodes.Cube010_3.geometry} material={materials.silver} />
      </group>
      <group position={[-2.722, -3.576, 1.097]}>
        <mesh
          geometry={nodes.Cube010_1.geometry}
          material={materials["wood.001"]}
        />
        <mesh
          geometry={nodes.Cube010_2.geometry}
          material={materials.silver02}
        />
        <mesh geometry={nodes.Cube010_3.geometry} material={materials.silver} />
      </group>
      <group position={[-0.723, 4.424, 1.097]}>
        <mesh
          geometry={nodes.Cube010_1.geometry}
          material={materials["wood.001"]}
        />
        <mesh
          geometry={nodes.Cube010_2.geometry}
          material={materials.silver02}
        />
        <mesh geometry={nodes.Cube010_3.geometry} material={materials.silver} />
      </group>
      <group position={[-0.723, 2.425, 1.097]}>
        <mesh
          geometry={nodes.Cube010_1.geometry}
          material={materials["wood.001"]}
        />
        <mesh
          geometry={nodes.Cube010_2.geometry}
          material={materials.silver02}
        />
        <mesh geometry={nodes.Cube010_3.geometry} material={materials.silver} />
      </group>
      <group position={[-0.723, 0.423, 1.097]}>
        <mesh
          geometry={nodes.Cube010_1.geometry}
          material={materials["wood.001"]}
        />
        <mesh
          geometry={nodes.Cube010_2.geometry}
          material={materials.silver02}
        />
        <mesh geometry={nodes.Cube010_3.geometry} material={materials.silver} />
      </group>
      <group position={[-0.723, -1.581, 1.097]}>
        <mesh
          geometry={nodes.Cube010_1.geometry}
          material={materials["wood.001"]}
        />
        <mesh
          geometry={nodes.Cube010_2.geometry}
          material={materials.silver02}
        />
        <mesh geometry={nodes.Cube010_3.geometry} material={materials.silver} />
      </group>
      <group position={[-0.723, -3.576, 1.097]}>
        <mesh
          geometry={nodes.Cube010_1.geometry}
          material={materials["wood.001"]}
        />
        <mesh
          geometry={nodes.Cube010_2.geometry}
          material={materials.silver02}
        />
        <mesh geometry={nodes.Cube010_3.geometry} material={materials.silver} />
      </group>
      <group position={[1.28, 4.424, 1.097]}>
        <mesh
          geometry={nodes.Cube010_1.geometry}
          material={materials["wood.001"]}
        />
        <mesh
          geometry={nodes.Cube010_2.geometry}
          material={materials.silver02}
        />
        <mesh geometry={nodes.Cube010_3.geometry} material={materials.silver} />
      </group>
      <group position={[1.28, 2.425, 1.097]}>
        <mesh
          geometry={nodes.Cube010_1.geometry}
          material={materials["wood.001"]}
        />
        <mesh
          geometry={nodes.Cube010_2.geometry}
          material={materials.silver02}
        />
        <mesh geometry={nodes.Cube010_3.geometry} material={materials.silver} />
      </group>
      <group position={[1.28, 0.423, 1.097]}>
        <mesh
          geometry={nodes.Cube010_1.geometry}
          material={materials["wood.001"]}
        />
        <mesh
          geometry={nodes.Cube010_2.geometry}
          material={materials.silver02}
        />
        <mesh geometry={nodes.Cube010_3.geometry} material={materials.silver} />
      </group>
      <group position={[1.28, -1.581, 1.097]}>
        <mesh
          geometry={nodes.Cube010_1.geometry}
          material={materials["wood.001"]}
        />
        <mesh
          geometry={nodes.Cube010_2.geometry}
          material={materials.silver02}
        />
        <mesh geometry={nodes.Cube010_3.geometry} material={materials.silver} />
      </group>
      <group position={[1.28, -3.576, 1.097]}>
        <mesh
          geometry={nodes.Cube010_1.geometry}
          material={materials["wood.001"]}
        />
        <mesh
          geometry={nodes.Cube010_2.geometry}
          material={materials.silver02}
        />
        <mesh geometry={nodes.Cube010_3.geometry} material={materials.silver} />
      </group>
      <group position={[3.279, 4.424, 1.097]}>
        <mesh
          geometry={nodes.Cube010_1.geometry}
          material={materials["wood.001"]}
        />
        <mesh
          geometry={nodes.Cube010_2.geometry}
          material={materials.silver02}
        />
        <mesh geometry={nodes.Cube010_3.geometry} material={materials.silver} />
      </group>
      <group position={[3.279, 2.425, 1.097]}>
        <mesh
          geometry={nodes.Cube010_1.geometry}
          material={materials["wood.001"]}
        />
        <mesh
          geometry={nodes.Cube010_2.geometry}
          material={materials.silver02}
        />
        <mesh geometry={nodes.Cube010_3.geometry} material={materials.silver} />
      </group>
      <group position={[3.279, 0.423, 1.097]}>
        <mesh
          geometry={nodes.Cube010_1.geometry}
          material={materials["wood.001"]}
        />
        <mesh
          geometry={nodes.Cube010_2.geometry}
          material={materials.silver02}
        />
        <mesh geometry={nodes.Cube010_3.geometry} material={materials.silver} />
      </group>
      <group position={[3.279, -1.581, 1.097]}>
        <mesh
          geometry={nodes.Cube010_1.geometry}
          material={materials["wood.001"]}
        />
        <mesh
          geometry={nodes.Cube010_2.geometry}
          material={materials.silver02}
        />
        <mesh geometry={nodes.Cube010_3.geometry} material={materials.silver} />
      </group>
      <group position={[3.279, -3.576, 1.097]}>
        <mesh
          geometry={nodes.Cube010_1.geometry}
          material={materials["wood.001"]}
        />
        <mesh
          geometry={nodes.Cube010_2.geometry}
          material={materials.silver02}
        />
        <mesh geometry={nodes.Cube010_3.geometry} material={materials.silver} />
      </group>
    </group>
  );
}

useGLTF.preload(
  "https://nogson.github.io/glb-viewer/ui-src/assets/glb/Locker.glb"
);
