/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ui-src/assets/glb/Locker.glb -o ui-src/components/Locker.tsx -r 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {}
  materials: {}
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('https://nogson.github.io/glb-viewer/ui-src/assets/glb/Locker.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group />
    </group>
  )
}

useGLTF.preload('https://nogson.github.io/glb-viewer/ui-src/assets/glb/Locker.glb')
