/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ui-src/assets/glb/Shower.glb -o ui-src/components/Shower.tsx 
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh;
    Cylinder001: THREE.Mesh;
    Cube001: THREE.Mesh;
    Plane: THREE.Mesh;
    Cylinder: THREE.Mesh;
    Cylinder005: THREE.Mesh;
    Cylinder005_1: THREE.Mesh;
    Cube002: THREE.Mesh;
    BezierCurve: THREE.Mesh;
    Cylinder003: THREE.Mesh;
  };
  materials: {
    ["floor.002"]: THREE.MeshStandardMaterial;
    ["Material.002"]: THREE.MeshStandardMaterial;
    ["floor.001"]: THREE.MeshStandardMaterial;
    ["Material.001"]: THREE.MeshStandardMaterial;
    Material: THREE.MeshStandardMaterial;
    ["Material.003"]: THREE.MeshStandardMaterial;
    ["Material.003"]: THREE.MeshStandardMaterial;
    ["Material.004"]: THREE.MeshStandardMaterial;
  };
};

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements["mesh"]>
>;

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "https://nogson.github.io/glb-viewer/ui-src/assets/glb/Shower.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials["floor.002"]} />
      <mesh
        geometry={nodes.Cylinder001.geometry}
        material={materials["Material.002"]}
        position={[-0.06, 0.782, 1.18]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.145, 0.373, 0.145]}
      />
      <mesh
        geometry={nodes.Cube001.geometry}
        material={materials["floor.001"]}
        position={[0, 2.436, 0]}
        scale={[1.946, 1.482, 0.338]}
      />
      <mesh
        geometry={nodes.Plane.geometry}
        material={materials["Material.001"]}
        position={[0, 2.526, 0.33]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[1.232, 1, 1.024]}
      />
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={materials["Material.002"]}
        position={[1.548, 2.746, 0.597]}
        rotation={[0.213, 0, 0]}
      />
      <group
        position={[1.549, 2.752, 0.485]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.185, 0.051, 0.185]}
      >
        <mesh
          geometry={nodes.Cylinder005.geometry}
          material={materials.Material}
        />
        <mesh
          geometry={nodes.Cylinder005_1.geometry}
          material={materials["Material.003"]}
        />
      </group>
      <mesh
        geometry={nodes.Cube002.geometry}
        material={materials["Material.002"]}
        position={[1.547, 2.446, 0.432]}
        scale={[0.12, 0.119, 0.119]}
      />
      <mesh
        geometry={nodes.BezierCurve.geometry}
        material={materials["Material.003"]}
        position={[0, 1.351, 1.041]}
      />
      <mesh
        geometry={nodes.Cylinder003.geometry}
        material={materials["Material.004"]}
        position={[1.548, 2.755, 0.555]}
        rotation={[0.213, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload(
  "https://nogson.github.io/glb-viewer/ui-src/assets/glb/Shower.glb"
);
